name: Linter

on: [push, pull_request]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.0.0
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm ci
      - name: Lint
        run: |
          npm run lint
        env:
          CI: true
